version: '3.9'
services:
  blog-database:
    build:
      context: .
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog
    volumes:
      - blog-db-vol:/var/lib/postgresql/data
volumes:
  blog-db-vol: